export enum LANG {
  uz = 'uz',
  oz = 'oz',
}

export enum STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DELETED = 'DELETED',
}

export enum TypeSearch {
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  BOOLEAN = 'BOOLEAN',
}

export enum OperationType {
  EQUAL = '=',
  NOT_EQUAL = '!=',
  GREATER_THAN = '>',
  LESS_THAN = '<',
  GREATER_THAN_OR_EQUAL = '>=',
  LESS_THAN_OR_EQUAL = '<=',
  IN = 'in',
  LIKE = 'LIKE',
  WILDCARD = '%_%',
}

export enum LANG_TYPE {
  ADMIN_CABINET = 'ADMIN_CABINET',
  CLIENT_CABINET = 'CLIENT_CABINET',
}

export enum Permissions {
  // Dashboard
  DASHBOARD_VIEW = 'DASHBOARD_VIEW',

  // Users
  VIEW_USERS = 'VIEW_USERS',
  VIEW_USER = 'VIEW_USER',
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  // Roles
  VIEW_ROLES = 'VIEW_ROLES',
  VIEW_ROLE = 'VIEW_ROLE',
  CREATE_ROLE = 'CREATE_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',

  // Translations
  VIEW_TRANSLATIONS = 'VIEW_TRANSLATIONS',
  VIEW_TRANSLATION = 'VIEW_TRANSLATION',
  CREATE_TRANSLATION = 'CREATE_TRANSLATION',
  UPDATE_TRANSLATION = 'UPDATE_TRANSLATION',
  DELETE_TRANSLATION = 'DELETE_TRANSLATION',
}
